# Generated by Django 2.2.15 on 2020-08-10 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_demomodel10123'),
    ]

    operations = [
        migrations.AddField(
            model_name='anothermodel',
            name='newField',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anothermodel_newField', to='home.CustomText'),
        ),
        migrations.AddField(
            model_name='demomodel101',
            name='demoFieldModel101',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demomodel101_demoFieldModel101', to='home.DemoModel10123'),
        ),
    ]
